/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Place } from './place';


export interface Day { 
    id?: number;
    place?: Place;
    date?: string;
    amountOfVisitors?: number;
    firstResponder?: number;
    reanimations?: number;
    aed?: number;
    helpPersons?: number;
    wasMedical?: number;
    wasLifeThreatening?: number;
    wasInWater?: number;
    wasLifeThreateningForHelper?: number;
    wasDead?: number;
    wasDrowned?: number;
    helpThings?: number;
    helpEnvironment?: number;
    helpAnimals?: number;
}

