/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Person { 
    id?: number;
    firstname: string;
    lastname: string;
    status?: Person.StatusEnum;
    lifeguard?: Person.LifeguardEnum;
    lifeguardFrom?: string;
    fitness?: string;
}
export namespace Person {
    export type StatusEnum = 'ILL' | 'RETIRED' | 'ACTIVE';
    export const StatusEnum = {
        Ill: 'ILL' as StatusEnum,
        Retired: 'RETIRED' as StatusEnum,
        Active: 'ACTIVE' as StatusEnum
    };
    export type LifeguardEnum = 'NONE' | 'JUNIOR' | 'BRONZE' | 'SILVER' | 'GOLD';
    export const LifeguardEnum = {
        None: 'NONE' as LifeguardEnum,
        Junior: 'JUNIOR' as LifeguardEnum,
        Bronze: 'BRONZE' as LifeguardEnum,
        Silver: 'SILVER' as LifeguardEnum,
        Gold: 'GOLD' as LifeguardEnum
    };
}


