/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Presence } from './presence';
import { Day } from './day';
import { Person } from './person';
import { Place } from './place';


export interface Summary { 
    created: string;
    day: Day;
    persons: Set<Person>;
    place: Place;
    presences: Array<Presence>;
    totalSeconds: number;
    totalHours: number;
    openPresences: number;
}

