export * from './achievementController.service';
import { AchievementControllerService } from './achievementController.service';
export * from './dutyController.service';
import { DutyControllerService } from './dutyController.service';
export * from './personController.service';
import { PersonControllerService } from './personController.service';
export * from './placeController.service';
import { PlaceControllerService } from './placeController.service';
export * from './presenceController.service';
import { PresenceControllerService } from './presenceController.service';
export * from './summaryController.service';
import { SummaryControllerService } from './summaryController.service';
export const APIS = [AchievementControllerService, DutyControllerService, PersonControllerService, PlaceControllerService, PresenceControllerService, SummaryControllerService];
